services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Beccati\PgSchemaBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

    beccati_pg_schema.manager.database:
        alias: Beccati\PgSchemaBundle\Manager\DatabaseManager
        public: true

    beccati_pg_schema.manager.upgrade:
        alias: Beccati\PgSchemaBundle\Manager\UpgradeManager
        public: true
